version: "2.3"
services:
  dit-service:
    container_name: dit-service
    image: dit-service
    network_mode: host
    privileged: true
    build:
      network: host
      context: ../
      dockerfile: docker/Dockerfile
      args:
        http_proxy: 
        https_proxy: 
        no_proxy: 
        socks_proxy:
  registry:
    container_name: registry
    image: registry:2
    network_mode: host
    ports:
      - "5000"